### ISSUE TITLE
ServerChecker v4

### ISSUE THREAD

**Issue by H1GHGuY** [m-ober/ServerChecker#1]
Hi Micha,

Apparently this is the quickest way to reach you regarding ServerChecker...
You might want to check this out:
https://github.com/H1GHGuY/ServerCheckerV4

Regards,
H!GHGuY

**Comment by m-ober** [comment]
Hi,

oh, well - I cannot quite understand how I was unable to find this.
I searched a lot to see whether there was still some development going 
on, or a newer version, but everyone and everything was just referencing 
to the (now defunct) http://www.dumbclan.co.uk/ page.

I will have a look at your new version, but until now the old version 
has been doing a great job for me ;-)

BR,
Micha

**Comment by H1GHGuY** [comment]
The new version is great... It just needs finishing up ;)
Even if you don't use it or don't finish it up, there's some really nice code in there that can be reused (if you mind the license).

Regards,
H!GHGuY

**Comment by m-ober** [comment]
README updated
